[package]
name = "echo-test"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
testsi = { workspace = true }
types = { workspace = true }

alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
