[package]
name = "testsi-macros"
edition.workspace = true
license.workspace = true
version.workspace = true

publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
