[package]
name = "test-case"
version = "0.1.0"
edition = "2021"

# [[test]]
# name = "entrypoint"
# path = "src/entrypoint.rs"

[dependencies]
testsi = { path = "../testsi" }

alloy-sol-types = "0.4"
alloy-primitives = "0.4"

[profile.dev]
incremental = false

[profile.release]
codegen-units = 1
